name: MooTools FileManager
author: cpojer
category: Interface
tags: [filemanager, upload, gallery, images]
demo: http://cpojer.net/Scripts/FileManager/Demos/
requires:
	core/1.2.4: '*'
	more/1.2.4.2: [Drag, Drag.Move, Tips, Assets, Element.Delegation]